propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
    
  localidad:
    nombre_localidad: { primaryString: true }
  
  tipo_ente:
    tipo_ente: { primaryString: true }
  
  estado_persona:
    estado: { primaryString: true }
      
  ejercicio_economico:
    id_ejercicio_economico: { primaryString: true }
  
  direccion:
    id_direccion: { primaryString: true }
  
  provincia:
    nombre_provincia: { primaryString: true }
  
  
  
  
