propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  actividad:
    _attributes: { phpName: Actividad, idMethod: native }
    id_actividad: { phpName: IdActividad, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    actividad: { phpName: Actividad, type: VARCHAR, size: '50', required: true }
  actividad_pers_juridica:
    _attributes: { phpName: ActividadPersJuridica, idMethod: native }
    actividad_id: { phpName: ActividadId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: actividad, foreignReference: id_actividad }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica }
    _indexes: { fk_actividad_pers_juridica_actividad1: [actividad_id], fk_actividad_pers_juridica_persona_juridica1: [persona_juridica_id] }
  direccion:
    _attributes: { phpName: Direccion, idMethod: native }
    id_direccion: { phpName: IdDireccion, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    localidad_id: { phpName: LocalidadId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: localidad, foreignReference: id_localidad }
    calle: { phpName: Calle, type: VARCHAR, size: '45', required: true }
    numero: { phpName: Numero, type: VARCHAR, size: '10', required: true }
    piso: { phpName: Piso, type: VARCHAR, size: '5', required: false }
    departamento: { phpName: Departamento, type: VARCHAR, size: '5', required: false }
    _indexes: { fk_direccion_localidad1: [localidad_id] }
  ejercicio_economico:
    _attributes: { phpName: EjercicioEconomico, idMethod: native }
    id_ejercicio_economico: { phpName: IdEjercicioEconomico, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    fecha_inicio: { phpName: FechaInicio, type: DATE, required: true }
    fecha_fin: { phpName: FechaFin, type: DATE, required: true }
    presidente: { phpName: Presidente, type: VARCHAR, size: '45', required: false }
    secretario: { phpName: Secretario, type: VARCHAR, size: '45', required: false }
    tesorero: { phpName: Tesorero, type: VARCHAR, size: '45', required: false }
    sindico: { phpName: Sindico, type: VARCHAR, size: '45', required: false }
  estado_persona:
    _attributes: { phpName: EstadoPersona, idMethod: native }
    id_estado_persona: { phpName: IdEstadoPersona, type: INTEGER, size: '1', sqlType: 'int(1) unsigned', primaryKey: true, autoIncrement: true, required: true }
    estado: { phpName: Estado, type: VARCHAR, size: '45', required: true, index: unique }
  localidad:
    _attributes: { phpName: Localidad, idMethod: native }
    id_localidad: { phpName: IdLocalidad, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_localidad: { phpName: NombreLocalidad, type: VARCHAR, size: '45', required: true }
    codigo_postal: { phpName: CodigoPostal, type: VARCHAR, size: '15', required: true }
    provincia_id: { phpName: ProvinciaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: provincia, foreignReference: id_provincia }
    _indexes: { fk_localidad_provincia1: [provincia_id] }
  persona:
    _attributes: { phpName: Persona, idMethod: native }
    id_persona: { phpName: IdPersona, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    estado_id: { phpName: EstadoId, type: INTEGER, size: '1', sqlType: 'int(1) unsigned', required: true, foreignTable: estado_persona, foreignReference: id_estado_persona }
    direccion_postal_id: { phpName: DireccionPostalId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: direccion, foreignReference: id_direccion }
    direccion_real_id: { phpName: DireccionRealId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: direccion, foreignReference: id_direccion }
    cuit_cuil: { phpName: CuitCuil, type: INTEGER, sqlType: 'int(11) unsigned', required: true }
    _indexes: { fk_persona_estado_persona1: [estado_id], fk_persona_direccion1: [direccion_postal_id], fk_persona_direccion2: [direccion_real_id] }
    _uniques: { id_tipoPers_UNIQUE: [cuit_cuil] }
  persona_fisica:
    _attributes: { phpName: PersonaFisica, idMethod: native }
    id_persona_fisica: { phpName: IdPersonaFisica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true, index: unique }
    persona_id: { phpName: PersonaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona, foreignReference: id_persona }
    nombre: { phpName: Nombre, type: VARCHAR, size: '25', required: false }
    apellido: { phpName: Apellido, type: VARCHAR, size: '30', required: false }
    usuario: { phpName: Usuario, type: VARCHAR, size: '20', required: true, index: unique }
    password: { phpName: Password, type: VARCHAR, size: '15', required: true }
    _indexes: { fk_persona_fisica_persona1: [persona_id] }
  persona_juridica:
    _attributes: { phpName: PersonaJuridica, idMethod: native }
    id_persona_juridica: { phpName: IdPersonaJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_id: { phpName: PersonaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona, foreignReference: id_persona }
    ejercicio_economico_id: { phpName: EjercicioEconomicoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: ejercicio_economico, foreignReference: id_ejercicio_economico }
    situacion_id: { phpName: SituacionId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: situacion_persona_juridica, foreignReference: id_situacion_pers_juridica, index: unique }
    tipo_pers_juridica_id: { phpName: TipoPersJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: tipo_persona_juridica, foreignReference: id_tipo_persona_juridica }
    nombre_fantasia: { phpName: NombreFantasia, type: VARCHAR, size: '45', required: true }
    fecha_inicio_actividad: { phpName: FechaInicioActividad, type: DATE, required: true }
    resenia: { phpName: Resenia, type: VARCHAR, size: '250', required: false }
    legajo: { phpName: Legajo, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, index: unique }
    matricula: { phpName: Matricula, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, index: unique }
    _indexes: { fk_persona_juridica_tipo_persona_juridica1: [tipo_pers_juridica_id], fk_persona_juridica_ejercicio_economico1: [ejercicio_economico_id], fk_persona_juridica_persona1: [persona_id] }
  provincia:
    _attributes: { phpName: Provincia, idMethod: native }
    id_provincia: { phpName: IdProvincia, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_provincia: { phpName: NombreProvincia, type: VARCHAR, size: '30', required: true }
  situacion_persona_juridica:
    _attributes: { phpName: SituacionPersonaJuridica, idMethod: native }
    id_situacion_pers_juridica: { phpName: IdSituacionPersJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    situacion: { phpName: Situacion, type: VARCHAR, size: '45', required: true }
  tipo_persona_juridica:
    _attributes: { phpName: TipoPersonaJuridica, idMethod: native }
    id_tipo_persona_juridica: { phpName: IdTipoPersonaJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_persona_juridica: { phpName: TipoPersonaJuridica, type: VARCHAR, size: '45', required: true }
