propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  actividad:
    _attributes: { phpName: Actividad, idMethod: native }
    id_actividad: { phpName: IdActividad, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    actividad: { phpName: Actividad, type: VARCHAR, size: '50', required: true, index: unique }
  actividad_pers_juridica:
    _attributes: { phpName: ActividadPersJuridica, idMethod: native }
    actividad_id: { phpName: ActividadId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: actividad, foreignReference: id_actividad, onDelete: CASCADE, onUpdate: CASCADE }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { fk_actividad_pers_juridica_actividad1: [actividad_id], fk_actividad_pers_juridica_persona_juridica1: [persona_juridica_id] }
  aporte:
    _attributes: { phpName: Aporte, idMethod: native }
    id_aporte: { phpName: IdAporte, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    tipo_aporte_id: { phpName: TipoAporteId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: tipo_aporte, foreignReference: id_tipo_aporte, onUpdate: CASCADE }
    fecha_aporte: { phpName: FechaAporte, type: DATE, required: true }
    monto_aporte: { phpName: MontoAporte, type: DECIMAL, size: '9', scale: '2', required: true }
    numero_expediente: { phpName: NumeroExpediente, type: VARCHAR, size: '10', required: true }
    _indexes: { fk_aportes_persona_juridica1: [persona_juridica_id], fk_aporte_tipo_aporte1: [tipo_aporte_id] }
    _uniques: { expediente_UNIQUE: [numero_expediente] }
  asamblea:
    _attributes: { phpName: Asamblea, idMethod: native }
    id_asamblea: { phpName: IdAsamblea, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    ejercicio_economico_id: { phpName: EjercicioEconomicoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: ejercicio_economico, foreignReference: id_ejercicio_economico, onDelete: CASCADE, onUpdate: CASCADE }
    tipo_asamblea_id: { phpName: TipoAsambleaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: tipo_asamblea, foreignReference: id_tipo_asamblea, onUpdate: CASCADE }
    fecha_de_asamblea: { phpName: FechaDeAsamblea, type: DATE, required: true }
    fecha_de_convocatoria: { phpName: FechaDeConvocatoria, type: DATE, required: true }
    fecha_de_nuevo_mandato: { phpName: FechaDeNuevoMandato, type: DATE, required: false }
    observaciones: { phpName: Observaciones, type: VARCHAR, size: '250', required: false }
    _indexes: { fk_asamblea_tipo_asamblea1: [tipo_asamblea_id], fk_asamblea_ejercicio_economico1: [ejercicio_economico_id] }
  direccion:
    _attributes: { phpName: Direccion, idMethod: native }
    id_direccion: { phpName: IdDireccion, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    tipo_direccion_id: { phpName: TipoDireccionId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '1', foreignTable: tipo_direccion, foreignReference: id_tipo_direccion, onUpdate: CASCADE }
    localidad_id: { phpName: LocalidadId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: localidad, foreignReference: id_localidad, onDelete: CASCADE, onUpdate: CASCADE }
    calle: { phpName: Calle, type: VARCHAR, size: '45', required: true }
    numero: { phpName: Numero, type: VARCHAR, size: '10', required: true, defaultValue: S/N }
    piso: { phpName: Piso, type: VARCHAR, size: '5', required: false }
    departamento: { phpName: Departamento, type: VARCHAR, size: '5', required: false }
    _indexes: { fk_direccion_tipo_direccion1_idx: [tipo_direccion_id], fk_direccion_localidad1: [localidad_id], fk_direccion_persona_juridica1: [persona_juridica_id] }
  ejercicio_economico:
    _attributes: { phpName: EjercicioEconomico, idMethod: native }
    id_ejercicio_economico: { phpName: IdEjercicioEconomico, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    numero_ejercicio_economico: { phpName: NumeroEjercicioEconomico, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    fecha_fin_ejercicio_economico: { phpName: FechaFinEjercicioEconomico, type: DATE, required: true }
    observaciones: { phpName: Observaciones, type: LONGVARCHAR, required: false }
    resultado_economico: { phpName: ResultadoEconomico, type: DECIMAL, size: '11', scale: '2', required: false }
    _indexes: { fk_ejercicio_economico_persona_juridica1: [persona_juridica_id] }
  ente_alerta:
    _attributes: { phpName: EnteAlerta, idMethod: native }
    id_ente_alerta: { phpName: IdEnteAlerta, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    ente_id: { phpName: EnteId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    alerta_id: { phpName: AlertaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: mail_alerta, foreignReference: id_tipo_alerta, onDelete: CASCADE, onUpdate: CASCADE }
    fecha_envio: { phpName: FechaEnvio, type: DATE, required: true }
    usuario: { phpName: Usuario, type: VARCHAR, size: '20', required: true }
    _indexes: { fk_ente_alerta_persona_juridica1: [ente_id], fk_ente_alerta_alerta1: [alerta_id] }
  estatuto:
    _attributes: { phpName: Estatuto, idMethod: native }
    id_estatuto: { phpName: IdEstatuto, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_juridica_id: { phpName: PersonaJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE, index: unique }
    duracion_de_mandato: { phpName: DuracionDeMandato, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    duracion_ejercicio_economico: { phpName: DuracionEjercicioEconomico, type: INTEGER, required: true, defaultValue: '1' }
    dias_para_fecha_tope_asamblea: { phpName: DiasParaFechaTopeAsamblea, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    dias_para_fecha_tope_convocatoria: { phpName: DiasParaFechaTopeConvocatoria, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    dias_para_fecha_tope_nuevo_mandato: { phpName: DiasParaFechaTopeNuevoMandato, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    estatuto_pdf: { phpName: EstatutoPdf, type: VARCHAR, size: '45', required: false }
    _indexes: { fk_estatuto_persona_juridica1: [persona_juridica_id] }
  imagenes:
    _attributes: { phpName: Imagenes, idMethod: native }
    id_imagenes: { phpName: IdImagenes, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_juridica_id_persona_juridica: { phpName: PersonaJuridicaIdPersonaJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona_juridica, foreignReference: id_persona_juridica, onDelete: CASCADE, onUpdate: CASCADE }
    descripcion: { phpName: Descripcion, type: VARCHAR, size: '45', required: false }
    nombre_archivo: { phpName: NombreArchivo, type: VARCHAR, size: '45', required: true }
    _indexes: { fk_imagenes_persona_juridica1: [persona_juridica_id_persona_juridica] }
    _uniques: { 'nombre archivo_UNIQUE': [nombre_archivo] }
  localidad:
    _attributes: { phpName: Localidad, idMethod: native }
    id_localidad: { phpName: IdLocalidad, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_localidad: { phpName: NombreLocalidad, type: VARCHAR, size: '45', required: true, index: unique }
    codigo_postal: { phpName: CodigoPostal, type: VARCHAR, size: '15', required: false }
    provincia_id: { phpName: ProvinciaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: provincia, foreignReference: id_provincia, onUpdate: CASCADE }
    _indexes: { fk_localidad_provincia1: [provincia_id] }
  mail_alerta:
    _attributes: { phpName: MailAlerta, idMethod: native }
    id_tipo_alerta: { phpName: IdTipoAlerta, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_alerta: { phpName: TipoAlerta, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    dias_para_aviso: { phpName: DiasParaAviso, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '15' }
    cuerpo_mensaje: { phpName: CuerpoMensaje, type: LONGVARCHAR, required: true }
    _uniques: { tipo_alerta_id_UNIQUE: [tipo_alerta] }
  persona_comision_directiva:
    _attributes: { phpName: PersonaComisionDirectiva, idMethod: native }
    id_persona_comision_directiva: { phpName: IdPersonaComisionDirectiva, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    ejercicio_economico_id: { phpName: EjercicioEconomicoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: ejercicio_economico, foreignReference: id_ejercicio_economico, onDelete: CASCADE, onUpdate: CASCADE }
    puesto_id: { phpName: PuestoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: puesto_comision_directiva, foreignReference: id_puesto_comision_directiva, onUpdate: CASCADE }
    nombre_y_apellido: { phpName: NombreYApellido, type: VARCHAR, size: '60', required: true }
    telefono: { phpName: Telefono, type: VARCHAR, size: '15', required: false }
    email: { phpName: Email, type: VARCHAR, size: '45', required: false }
    fecha_inicio_actividad: { phpName: FechaInicioActividad, type: DATE, required: true }
    _indexes: { fk_persona_comision_directiva_puesto_comision_directiva1: [puesto_id], fk_persona_comision_directiva_ejercicio_economico1: [ejercicio_economico_id] }
  persona_fisica:
    _attributes: { phpName: PersonaFisica, idMethod: native }
    id_persona_fisica: { phpName: IdPersonaFisica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true, index: unique }
    tipo_usuario_id: { phpName: TipoUsuarioId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '3', foreignTable: tipo_usuario, foreignReference: id_tipo_usuario, onDelete: CASCADE, onUpdate: CASCADE }
    nombre: { phpName: Nombre, type: VARCHAR, size: '25', required: true }
    apellido: { phpName: Apellido, type: VARCHAR, size: '30', required: true }
    usuario: { phpName: Usuario, type: VARCHAR, size: '20', required: true, index: unique }
    password: { phpName: Password, type: LONGVARCHAR, required: true }
    _indexes: { fk_persona_fisica_tipo_usuario1: [tipo_usuario_id] }
  persona_juridica:
    _attributes: { phpName: PersonaJuridica, idMethod: native }
    id_persona_juridica: { phpName: IdPersonaJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    situacion_id: { phpName: SituacionId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '1', foreignTable: situacion_persona_juridica, foreignReference: id_situacion_pers_juridica, onUpdate: CASCADE }
    tipo_pers_juridica_id: { phpName: TipoPersJuridicaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '1', foreignTable: tipo_persona_juridica, foreignReference: id_tipo_persona_juridica, onUpdate: CASCADE }
    cuit_cuil: { phpName: CuitCuil, type: DECIMAL, size: '11', scale: '0', required: true, index: unique }
    nombre_fantasia: { phpName: NombreFantasia, type: VARCHAR, size: '45', required: true }
    fecha_inicio_actividad: { phpName: FechaInicioActividad, type: DATE, required: true }
    resenia: { phpName: Resenia, type: VARCHAR, size: '250', required: false }
    legajo: { phpName: Legajo, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, index: unique }
    matricula: { phpName: Matricula, type: VARCHAR, size: '10', required: false, index: unique }
    cantidad_de_socios: { phpName: CantidadDeSocios, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    telefono: { phpName: Telefono, type: VARCHAR, size: '25', required: true }
    email: { phpName: Email, type: VARCHAR, size: '25', required: true }
    _indexes: { fk_persona_juridica_tipo_persona_juridica1: [tipo_pers_juridica_id], fk_persona_juridica_situacion_persona_juridica1: [situacion_id] }
  provincia:
    _attributes: { phpName: Provincia, idMethod: native }
    id_provincia: { phpName: IdProvincia, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_provincia: { phpName: NombreProvincia, type: VARCHAR, size: '30', required: true, index: unique }
  puesto_comision_directiva:
    _attributes: { phpName: PuestoComisionDirectiva, idMethod: native }
    id_puesto_comision_directiva: { phpName: IdPuestoComisionDirectiva, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    puesto: { phpName: Puesto, type: VARCHAR, size: '45', required: true, index: unique }
  situacion_persona_juridica:
    _attributes: { phpName: SituacionPersonaJuridica, idMethod: native }
    id_situacion_pers_juridica: { phpName: IdSituacionPersJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    situacion: { phpName: Situacion, type: VARCHAR, size: '45', required: true, index: unique }
  tipo_aporte:
    _attributes: { phpName: TipoAporte, idMethod: native }
    id_tipo_aporte: { phpName: IdTipoAporte, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_aporte: { phpName: TipoAporte, type: VARCHAR, size: '45', required: true, index: unique }
  tipo_asamblea:
    _attributes: { phpName: TipoAsamblea, idMethod: native }
    id_tipo_asamblea: { phpName: IdTipoAsamblea, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_asamblea: { phpName: TipoAsamblea, type: VARCHAR, size: '45', required: true, index: unique }
  tipo_direccion:
    _attributes: { phpName: TipoDireccion, idMethod: native }
    id_tipo_direccion: { phpName: IdTipoDireccion, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    descripcion: { phpName: Descripcion, type: VARCHAR, size: '45', required: true, index: unique }
  tipo_persona_juridica:
    _attributes: { phpName: TipoPersonaJuridica, idMethod: native }
    id_tipo_persona_juridica: { phpName: IdTipoPersonaJuridica, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_persona_juridica: { phpName: TipoPersonaJuridica, type: VARCHAR, size: '45', required: true, index: unique }
  tipo_usuario:
    _attributes: { phpName: TipoUsuario, idMethod: native }
    id_tipo_usuario: { phpName: IdTipoUsuario, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    tipo_usuario: { phpName: TipoUsuario, type: VARCHAR, size: '45', required: true, index: unique }
