propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
    
  localidad:
    nombre_localidad: { primaryString: true }
  
  tipo_persona_juridica:
    tipo_persona_juridica: { primaryString: true }
  
  estado_persona:
    estado: { primaryString: true }
        
  direccion:
    calle: { primaryString: true }
  
  provincia:
    nombre_provincia: { primaryString: true }
  
  situacion_persona_juridica:
    situacion:  { primaryString: true }
  
  persona:
    cuit_cuil:  { primaryString: true }
